name: Build APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Download libv2ray
      run: |
        mkdir -p V2rayNG/app/libs/
        LATEST_TAG=$(curl -s https://api.github.com/repos/2dust/AndroidLibXrayLite/releases/latest | grep "tag_name" | cut -d '"' -f 4)
        echo "Latest tag: $LATEST_TAG"
        curl -L -o V2rayNG/app/libs/libv2ray.aar https://github.com/2dust/AndroidLibXrayLite/releases/download/${LATEST_TAG}/libv2ray.aar

    - name: Build APK
      run: |
        cd V2rayNG
        echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties
        chmod +x gradlew
        ./gradlew assembleRelease --stacktrace

    - name: Upload arm64-v8a APK
      uses: actions/upload-artifact@v4
      with:
        name: samal-v2ray-arm64
        path: V2rayNG/app/build/outputs/apk/*/release/*arm64-v8a*.apk

    - name: Upload universal APK
      uses: actions/upload-artifact@v4
      with:
        name: samal-v2ray-universal
        path: V2rayNG/app/build/outputs/apk/*/release/*universal*.apk
